FFT tests

In [26]:
from scipy.fftpack import fft, ifft
print(fft([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]))
print(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j]))

print(abs(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j])))

[4. +0.j         0.5-2.19064313j 0.5+0.24078731j 0.5-0.62698017j
 0.5+0.62698017j 0.5-0.24078731j 0.5+2.19064313j]
[1.00000000e+00+0.00000000e+00j 9.99999999e-01-5.55111512e-17j
 1.00000000e+00+0.00000000e+00j 9.99999999e-01-5.55111512e-17j
 0.00000000e+00+0.00000000e+00j 8.39015857e-10+5.55111512e-17j
 0.00000000e+00+0.00000000e+00j 8.39015857e-10+5.55111512e-17j]
[1.00000000e+00 9.99999999e-01 1.00000000e+00 9.99999999e-01
 0.00000000e+00 8.39015857e-10 0.00000000e+00 8.39015857e-10]


Numpy tests

In [1]:
import numpy as np
n = np.linspace(1.2,3)
print(len(n))
n

n = np.linspace(1.2,3, endpoint=False)
print(len(n))
n

n = np.linspace(1.2,3, num=3)
n

n = np.linspace(1.2,3, num=3, endpoint=False)
n

np.zeros(3)

50
50


array([0., 0., 0.])

Windowtests

In [8]:
from scipy import signal
w = signal.hann(10)
print(w)
print(len(w))

w2 = signal.hann(10, False)
print(w2)
print(len(w2))

[0.         0.11697778 0.41317591 0.75       0.96984631 0.96984631
 0.75       0.41317591 0.11697778 0.        ]
10
[0.        0.0954915 0.3454915 0.6545085 0.9045085 1.        0.9045085
 0.6545085 0.3454915 0.0954915]
10


In [9]:
w = [1,2,3]
print(w[:-1])

[1, 2]


In [11]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

[0.08       0.18761956 0.46012184 0.77       0.97225861 0.97225861
 0.77       0.46012184 0.18761956 0.08      ]
10
[0.08       0.16785218 0.39785218 0.68214782 0.91214782 1.
 0.91214782 0.68214782 0.39785218 0.16785218]
10


In [1]:
from scipy import signal
w = signal.blackman(10)
print(w)
print(len(w))

w2 = signal.blackman(10, False)
print(w2)
print(len(w2))

[-1.38777878e-17  5.08696327e-02  2.58000502e-01  6.30000000e-01
  9.51129866e-01  9.51129866e-01  6.30000000e-01  2.58000502e-01
  5.08696327e-02 -1.38777878e-17]
10
[-1.38777878e-17  4.02128624e-02  2.00770143e-01  5.09787138e-01
  8.49229857e-01  1.00000000e+00  8.49229857e-01  5.09787138e-01
  2.00770143e-01  4.02128624e-02]
10


In [3]:
from scipy import signal
w = signal.blackmanharris(10)
print(w)
print(len(w))

w2 = signal.blackmanharris(10, False)
print(w2)
print(len(w2))

[6.00000000e-05 1.50711734e-02 1.47039558e-01 5.20575000e-01
 9.31659269e-01 9.31659269e-01 5.20575000e-01 1.47039558e-01
 1.50711734e-02 6.00000000e-05]
10
[6.00000000e-05 1.09823313e-02 1.03011489e-01 3.85892669e-01
 7.93833511e-01 1.00000000e+00 7.93833511e-01 3.85892669e-01
 1.03011489e-01 1.09823313e-02]
10


In [5]:
from scipy import signal
w = signal.flattop(10)
print(w)
print(len(w))

w2 = signal.flattop(10, False)
print(w2)
print(len(w2))

[-4.21051000e-04 -2.01720315e-02 -7.01990421e-02  1.98210530e-01
  8.62476344e-01  8.62476344e-01  1.98210530e-01 -7.01990421e-02
 -2.01720315e-02 -4.21051000e-04]
10
[-4.21051000e-04 -1.55972747e-02 -6.77142521e-02  5.45446482e-02
  6.06872153e-01  1.00000000e+00  6.06872153e-01  5.45446482e-02
 -6.77142521e-02 -1.55972747e-02]
10


In [6]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

[0.08       0.18761956 0.46012184 0.77       0.97225861 0.97225861
 0.77       0.46012184 0.18761956 0.08      ]
10
[0.08       0.16785218 0.39785218 0.68214782 0.91214782 1.
 0.91214782 0.68214782 0.39785218 0.16785218]
10


In [7]:
from scipy import signal
w = signal.nuttall(10)
print(w)
print(len(w))

w2 = signal.nuttall(10, False)
print(w2)
print(len(w2))

[3.62800000e-04 1.78909987e-02 1.55596126e-01 5.29229800e-01
 9.33220225e-01 9.33220225e-01 5.29229800e-01 1.55596126e-01
 1.78909987e-02 3.62800000e-04]
10
[3.62800000e-04 1.33288369e-02 1.10515253e-01 3.95625913e-01
 7.98258097e-01 1.00000000e+00 7.98258097e-01 3.95625913e-01
 1.10515253e-01 1.33288369e-02]
10


In [27]:
from numpy.core.numeric import (
    absolute, asanyarray, arange, zeros, greater_equal, multiply, ones,
    asarray, where, int8, int16, int32, int64, empty, promote_types, diagonal,
    nonzero
    )

x = asarray([99,99,99])
N = len(x)
v = empty((len(x), N), dtype=promote_types(x.dtype, int))

print(v)

tmp = v[:, ::-1]

tmp[:, 1:] = x[:, None]

print(tmp)
print(x[:, None])

multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

[[9801   99    1]
 [9801   99    1]
 [9801   99    1]]
[[ 1 99 99]
 [ 1 99 99]
 [ 1 99 99]]
[[99]
 [99]
 [99]]


array([[  99, 9801],
       [  99, 9801],
       [  99, 9801]])

In [39]:
from numpy.lib.twodim_base import vander
print(vander([2,4,8], increasing = True))
print(vander([2,4,8]))

print(vander([2,4,8], N = 2, increasing = True))
print(vander([2,4,8], N = 2))

[[ 1  2  4]
 [ 1  4 16]
 [ 1  8 64]]
[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[[1 2]
 [1 4]
 [1 8]]
[[2 1]
 [4 1]
 [8 1]]


In [53]:
from numpy.lib.twodim_base import vander
import numpy as np
v = vander([2,4,8])
w = asarray([2,2,2])
print(v)
print(w[:, np.newaxis])
v * w[:, np.newaxis]

[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[[2]
 [2]
 [2]]


array([[  8,   4,   2],
       [ 32,   8,   2],
       [128,  16,   2]])

In [71]:
import numpy.core.numeric as NX
import numpy as np

lhs = vander([2,4,8])
print(lhs)
scale = NX.sqrt((lhs*lhs).sum(axis=0))
print(scale)
res = lhs / scale
print(res)

# a = np.array([[1,2,3],[1,2,3],[1,2,3]])
# b = np.array([[1],[2],[3]])

# print(a/b)

[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[66.09084657  9.16515139  1.73205081]
[[0.06052275 0.21821789 0.57735027]
 [0.24209101 0.43643578 0.57735027]
 [0.96836405 0.87287156 0.57735027]]


In [5]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
# a = np.array(((
#     (12, -51,   4),
#     ( 6, 167, -68),
#     (-4,  24, -41),
# )))

q, r = np.linalg.qr(a)
print(q)
print(r)

# q:
#  [[-0.857143  0.394286  0.331429]
#  [-0.428571 -0.902857 -0.034286]
#  [ 0.285714 -0.171429  0.942857]]
# r:
#  [[ -14.  -21.   14.]
#  [   0. -175.   70.]
#  [   0.    0.  -35.]]

[[-0.06052275 -0.6022239  -0.79602975]
 [-0.24209101 -0.76482436  0.59702231]
 [-0.96836405  0.22884508 -0.09950372]]
[[-66.09084657  -8.83632198  -1.27097782]
 [  0.          -2.43298457  -1.13820318]
 [  0.           0.          -0.29851116]]


In [5]:
import scipy.linalg as la

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])

p, l, u = la.lu(a)
print(l)
print(u)
print(p)

[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.0625 0.75   1.    ]]
[[64.     8.     1.   ]
 [ 0.     2.     0.75 ]
 [ 0.     0.     0.375]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [8]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

a = np.array([[1,2,3], [4,5,6], [7,8,10]])
b = np.array([9,4,6])
x = np.linalg.solve(a, b)
print(x)

[2. 3.]
[-5.33333333 -3.33333333  7.        ]


In [10]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.linalg.inv(a)
print(x)

[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [11]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.matrix.transpose(a)
print(x)

[[ 1  4  7]
 [ 2  5  8]
 [ 3  6 10]]


In [23]:
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 3)
print(z)

x = np.array([0.0, 1.0,  2.0,  3.0,  4.0,  5.0,   6.0,   7.0,   8.0,   9.0,  10.0]);
y = np.array([1.0, 6.0, 17.0, 34.0, 57.0, 86.0, 121.0, 162.0, 209.0, 262.0, 321.0]);
z = np.polyfit(x, y, 3)
print(z)

[ 0.08703704 -0.81349206  1.69312169 -0.03968254]
[1.62158198e-16 3.00000000e+00 2.00000000e+00 1.00000000e+00]


In [22]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
u, s, vh = np.linalg.svd(a, full_matrices=True)

print(u)
print(s)
print(vh)

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
u, s, vh = np.linalg.svd(a, full_matrices=True)
print()
print(u)
print(s)
print(vh)

[[-0.06370191 -0.63944931 -0.76618969]
 [-0.24598854 -0.73399958  0.63303575]
 [-0.96717718  0.22879947 -0.11054003]]
[66.69193778  2.66694684  0.26986934]
[[-0.99097382 -0.13268134 -0.01914576]
 [ 0.12800229 -0.89409402 -0.42919844]
 [-0.03982852  0.42777512 -0.90300727]]

[[-0.15248323 -0.82264747 -0.39450102 -0.37995913]
 [-0.34991837 -0.42137529  0.24279655  0.80065588]
 [-0.54735351 -0.0201031   0.69790998 -0.46143436]
 [-0.74478865  0.38116908 -0.5462055   0.04073761]]
[14.2690955   0.62682823]
[[-0.64142303 -0.7671874 ]
 [ 0.7671874  -0.64142303]]


In [39]:
import numpy as np

y = np.array([9,8,7,6])
x = np.array([1,3,1,1])
nd = y.ndim
print(y.shape)
print(len(y.shape))

axis = -1
dx = 1

# d = dx
d = np.diff(x)
print(d)

slice1 = [slice(None)]*nd
slice2 = [slice(None)]*nd
slice1[axis] = slice(1, None)
slice2[axis] = slice(None, -1)

print(slice1)
print(slice2)

print(tuple(slice1))
print(tuple(slice2))

print(y[tuple(slice1)])
print(y[tuple(slice2)])

print(np.trapz(y, x=x))

ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
print(ret)



(4,)
1
[ 2 -2  0]
[slice(1, None, None)]
[slice(None, -1, None)]
(slice(1, None, None),)
(slice(None, -1, None),)
[8 7 6]
[9 8 7]
2.0
2.0


In [67]:
def tupleset(t, i, value):
    l = list(t)
    l[i] = value
    return tuple(l)

y = np.array([9,8,7,6,5,4,3,2,1])
x = np.array([1,3,1,1])
axis = -1
dx = 1

N = y.shape[axis]
start = 0
stop = N - 2
step = 2

nd = len(y.shape)
if start is None:
    start = 0
step = 2
slice_all = (slice(None),)*nd
slice0 = tupleset(slice_all, axis, slice(start, stop, step))
slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

print(slice_all)
print(slice0)
print(slice1)
print(slice2)

print(y[slice0])
print(y[slice1])
print(y[slice2])

def _basic_simps(y, start, stop, x, dx, axis):
    nd = len(y.shape)
    if start is None:
        start = 0
    step = 2
    slice_all = (slice(None),)*nd
    slice0 = tupleset(slice_all, axis, slice(start, stop, step))
    slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
    slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

    if x is None:  # Even spaced Simpson's rule.
        result = np.sum(dx/3.0 * (y[slice0]+4*y[slice1]+y[slice2]),
                        axis=axis)
    else:
        # Account for possibly different spacings.
        #    Simpson's rule changes a bit.
        h = np.diff(x, axis=axis)
        sl0 = tupleset(slice_all, axis, slice(start, stop, step))
        sl1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
        h0 = h[sl0]
        h1 = h[sl1]
        hsum = h0 + h1
        hprod = h0 * h1
        h0divh1 = h0 / h1
        tmp = hsum/6.0 * (y[slice0]*(2-1.0/h0divh1) +
                          y[slice1]*hsum*hsum/hprod +
                          y[slice2]*(2-h0divh1))
        result = np.sum(tmp, axis=axis)
    return result

(slice(None, None, None),)
(slice(0, 7, 2),)
(slice(1, 8, 2),)
(slice(2, 9, 2),)
[9 7 5 3]
[8 6 4 2]
[7 5 3 1]
(0,)
(1,)


In [64]:
from scipy import integrate

axis = -1
dx = 1
print(integrate.simps(y))

x = np.arange(0, 10)
y = np.arange(0, 10)

N = y.shape[axis]
start = 0
stop = N - 2
step = 2
axis = -1
dx = 1

print(integrate.simps(y, x=x))
print(integrate.trapz(y, x=x))

print(_basic_simps(y, start, stop, x, dx, axis))

x = np.asarray(x)
if len(x.shape) == 1:
    shapex = [1] * nd
    shapex[axis] = x.shape[0]
    saveshape = x.shape
    returnshape = 1
    x = x.reshape(tuple(shapex))
print(x)

print(_basic_simps(y, start, stop, x, dx, axis))

print(N % 2 == 0)

40.5
40.5
40.5
32.0
[0 1 2 3 4 5 6 7 8 9]
32.0
True


In [79]:
slice1 = (slice(None),)*nd
slice2 = (slice(None),)*nd

print(x)

print(tupleset(slice1, axis, 0))
print(tupleset(slice2, axis, 1))

print(x[tuple(tupleset(slice1, axis, 0))])
print(x[tuple(tupleset(slice1, axis, 1))])

print(tupleset(slice1, axis, -1))
print(tupleset(slice2, axis, -2))
print(x[tuple(tupleset(slice1, axis, -1))])
print(x[tuple(tupleset(slice2, axis, -2))])

x = 0.0

x += np.array([1,2,3])
print(x + 50)

[1. 2. 3.]
(0,)
(1,)
1.0
2.0
(-1,)
(-2,)
3.0
2.0
[51. 52. 53.]
