FFT tests

In [2]:
from scipy.fftpack import fft, ifft
print(fft([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]))
print(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j]))

print(abs(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j])))

[4.+0.j         1.-2.41421356j 0.-0.j         1.-0.41421356j
 0.+0.j         1.+0.41421356j 0.+0.j         1.+2.41421356j]
[1.00000000e+00+0.00000000e+00j 9.99999999e-01-5.55111512e-17j
 1.00000000e+00+0.00000000e+00j 9.99999999e-01-5.55111512e-17j
 0.00000000e+00+0.00000000e+00j 8.39015857e-10+5.55111512e-17j
 0.00000000e+00+0.00000000e+00j 8.39015857e-10+5.55111512e-17j]
[1.00000000e+00 9.99999999e-01 1.00000000e+00 9.99999999e-01
 0.00000000e+00 8.39015857e-10 0.00000000e+00 8.39015857e-10]


Numpy tests

In [1]:
import numpy as np
n = np.linspace(1.2,3)
print(len(n))
n

n = np.linspace(1.2,3, endpoint=False)
print(len(n))
n

n = np.linspace(1.2,3, num=3)
n

n = np.linspace(1.2,3, num=3, endpoint=False)
n

np.zeros(3)

50
50


array([0., 0., 0.])

Windowtests

In [8]:
from scipy import signal
w = signal.hann(10)
print(w)
print(len(w))

w2 = signal.hann(10, False)
print(w2)
print(len(w2))

[0.         0.11697778 0.41317591 0.75       0.96984631 0.96984631
 0.75       0.41317591 0.11697778 0.        ]
10
[0.        0.0954915 0.3454915 0.6545085 0.9045085 1.        0.9045085
 0.6545085 0.3454915 0.0954915]
10


In [9]:
w = [1,2,3]
print(w[:-1])

[1, 2]


In [11]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

[0.08       0.18761956 0.46012184 0.77       0.97225861 0.97225861
 0.77       0.46012184 0.18761956 0.08      ]
10
[0.08       0.16785218 0.39785218 0.68214782 0.91214782 1.
 0.91214782 0.68214782 0.39785218 0.16785218]
10


In [1]:
from scipy import signal
w = signal.blackman(10)
print(w)
print(len(w))

w2 = signal.blackman(10, False)
print(w2)
print(len(w2))

[-1.38777878e-17  5.08696327e-02  2.58000502e-01  6.30000000e-01
  9.51129866e-01  9.51129866e-01  6.30000000e-01  2.58000502e-01
  5.08696327e-02 -1.38777878e-17]
10
[-1.38777878e-17  4.02128624e-02  2.00770143e-01  5.09787138e-01
  8.49229857e-01  1.00000000e+00  8.49229857e-01  5.09787138e-01
  2.00770143e-01  4.02128624e-02]
10


In [3]:
from scipy import signal
w = signal.blackmanharris(10)
print(w)
print(len(w))

w2 = signal.blackmanharris(10, False)
print(w2)
print(len(w2))

[6.00000000e-05 1.50711734e-02 1.47039558e-01 5.20575000e-01
 9.31659269e-01 9.31659269e-01 5.20575000e-01 1.47039558e-01
 1.50711734e-02 6.00000000e-05]
10
[6.00000000e-05 1.09823313e-02 1.03011489e-01 3.85892669e-01
 7.93833511e-01 1.00000000e+00 7.93833511e-01 3.85892669e-01
 1.03011489e-01 1.09823313e-02]
10


In [5]:
from scipy import signal
w = signal.flattop(10)
print(w)
print(len(w))

w2 = signal.flattop(10, False)
print(w2)
print(len(w2))

[-4.21051000e-04 -2.01720315e-02 -7.01990421e-02  1.98210530e-01
  8.62476344e-01  8.62476344e-01  1.98210530e-01 -7.01990421e-02
 -2.01720315e-02 -4.21051000e-04]
10
[-4.21051000e-04 -1.55972747e-02 -6.77142521e-02  5.45446482e-02
  6.06872153e-01  1.00000000e+00  6.06872153e-01  5.45446482e-02
 -6.77142521e-02 -1.55972747e-02]
10


In [6]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

[0.08       0.18761956 0.46012184 0.77       0.97225861 0.97225861
 0.77       0.46012184 0.18761956 0.08      ]
10
[0.08       0.16785218 0.39785218 0.68214782 0.91214782 1.
 0.91214782 0.68214782 0.39785218 0.16785218]
10


In [7]:
from scipy import signal
w = signal.nuttall(10)
print(w)
print(len(w))

w2 = signal.nuttall(10, False)
print(w2)
print(len(w2))

[3.62800000e-04 1.78909987e-02 1.55596126e-01 5.29229800e-01
 9.33220225e-01 9.33220225e-01 5.29229800e-01 1.55596126e-01
 1.78909987e-02 3.62800000e-04]
10
[3.62800000e-04 1.33288369e-02 1.10515253e-01 3.95625913e-01
 7.98258097e-01 1.00000000e+00 7.98258097e-01 3.95625913e-01
 1.10515253e-01 1.33288369e-02]
10


In [27]:
from numpy.core.numeric import (
    absolute, asanyarray, arange, zeros, greater_equal, multiply, ones,
    asarray, where, int8, int16, int32, int64, empty, promote_types, diagonal,
    nonzero
    )

x = asarray([99,99,99])
N = len(x)
v = empty((len(x), N), dtype=promote_types(x.dtype, int))

print(v)

tmp = v[:, ::-1]

tmp[:, 1:] = x[:, None]

print(tmp)
print(x[:, None])

multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

[[9801   99    1]
 [9801   99    1]
 [9801   99    1]]
[[ 1 99 99]
 [ 1 99 99]
 [ 1 99 99]]
[[99]
 [99]
 [99]]


array([[  99, 9801],
       [  99, 9801],
       [  99, 9801]])

In [39]:
from numpy.lib.twodim_base import vander
print(vander([2,4,8], increasing = True))
print(vander([2,4,8]))

print(vander([2,4,8], N = 2, increasing = True))
print(vander([2,4,8], N = 2))

[[ 1  2  4]
 [ 1  4 16]
 [ 1  8 64]]
[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[[1 2]
 [1 4]
 [1 8]]
[[2 1]
 [4 1]
 [8 1]]


In [53]:
from numpy.lib.twodim_base import vander
import numpy as np
v = vander([2,4,8])
w = asarray([2,2,2])
print(v)
print(w[:, np.newaxis])
v * w[:, np.newaxis]

[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[[2]
 [2]
 [2]]


array([[  8,   4,   2],
       [ 32,   8,   2],
       [128,  16,   2]])

In [71]:
import numpy.core.numeric as NX
import numpy as np

lhs = vander([2,4,8])
print(lhs)
scale = NX.sqrt((lhs*lhs).sum(axis=0))
print(scale)
res = lhs / scale
print(res)

# a = np.array([[1,2,3],[1,2,3],[1,2,3]])
# b = np.array([[1],[2],[3]])

# print(a/b)

[[ 4  2  1]
 [16  4  1]
 [64  8  1]]
[66.09084657  9.16515139  1.73205081]
[[0.06052275 0.21821789 0.57735027]
 [0.24209101 0.43643578 0.57735027]
 [0.96836405 0.87287156 0.57735027]]


In [5]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
# a = np.array(((
#     (12, -51,   4),
#     ( 6, 167, -68),
#     (-4,  24, -41),
# )))

q, r = np.linalg.qr(a)
print(q)
print(r)

# q:
#  [[-0.857143  0.394286  0.331429]
#  [-0.428571 -0.902857 -0.034286]
#  [ 0.285714 -0.171429  0.942857]]
# r:
#  [[ -14.  -21.   14.]
#  [   0. -175.   70.]
#  [   0.    0.  -35.]]

[[-0.06052275 -0.6022239  -0.79602975]
 [-0.24209101 -0.76482436  0.59702231]
 [-0.96836405  0.22884508 -0.09950372]]
[[-66.09084657  -8.83632198  -1.27097782]
 [  0.          -2.43298457  -1.13820318]
 [  0.           0.          -0.29851116]]


In [5]:
import scipy.linalg as la

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])

p, l, u = la.lu(a)
print(l)
print(u)
print(p)

[[1.     0.     0.    ]
 [0.25   1.     0.    ]
 [0.0625 0.75   1.    ]]
[[64.     8.     1.   ]
 [ 0.     2.     0.75 ]
 [ 0.     0.     0.375]]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
