FFT tests

In [ ]:
from scipy.fftpack import fft, ifft
print(fft([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0]))
print(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j]))

print(abs(ifft([4.+0.j, 1.-2.41421356j, 0.-0.j, 1.-0.41421356j, 0.+0.j, 1.+0.41421356j, 0.+0.j, 1.+2.41421356j])))

Numpy tests

In [ ]:
import numpy as np
n = np.linspace(1.2,3)
print(len(n))
n

n = np.linspace(1.2,3, endpoint=False)
print(len(n))
n

n = np.linspace(1.2,3, num=3)
n

n = np.linspace(1.2,3, num=3, endpoint=False)
n

np.zeros(3)

Windowtests

In [ ]:
from scipy import signal
w = signal.hann(10)
print(w)
print(len(w))

w2 = signal.hann(10, False)
print(w2)
print(len(w2))

In [ ]:
w = [1,2,3]
print(w[:-1])

In [ ]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.blackman(10)
print(w)
print(len(w))

w2 = signal.blackman(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.blackmanharris(10)
print(w)
print(len(w))

w2 = signal.blackmanharris(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.flattop(10)
print(w)
print(len(w))

w2 = signal.flattop(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.hamming(10)
print(w)
print(len(w))

w2 = signal.hamming(10, False)
print(w2)
print(len(w2))

In [ ]:
from scipy import signal
w = signal.nuttall(10)
print(w)
print(len(w))

w2 = signal.nuttall(10, False)
print(w2)
print(len(w2))

In [ ]:
from numpy.core.numeric import (
    absolute, asanyarray, arange, zeros, greater_equal, multiply, ones,
    asarray, where, int8, int16, int32, int64, empty, promote_types, diagonal,
    nonzero
    )

x = asarray([99,99,99])
N = len(x)
v = empty((len(x), N), dtype=promote_types(x.dtype, int))

print(v)

tmp = v[:, ::-1]

tmp[:, 1:] = x[:, None]

print(tmp)
print(x[:, None])

multiply.accumulate(tmp[:, 1:], out=tmp[:, 1:], axis=1)

In [ ]:
from numpy.lib.twodim_base import vander
print(vander([2,4,8], increasing = True))
print(vander([2,4,8]))

print(vander([2,4,8], N = 2, increasing = True))
print(vander([2,4,8], N = 2))

In [ ]:
from numpy.lib.twodim_base import vander
import numpy as np
v = vander([2,4,8])
w = asarray([2,2,2])
print(v)
print(w[:, np.newaxis])
v * w[:, np.newaxis]

In [ ]:
import numpy.core.numeric as NX
import numpy as np

lhs = vander([2,4,8])
print(lhs)
scale = NX.sqrt((lhs*lhs).sum(axis=0))
print(scale)
res = lhs / scale
print(res)

# a = np.array([[1,2,3],[1,2,3],[1,2,3]])
# b = np.array([[1],[2],[3]])

# print(a/b)

In [ ]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
# a = np.array(((
#     (12, -51,   4),
#     ( 6, 167, -68),
#     (-4,  24, -41),
# )))

q, r = np.linalg.qr(a)
print(q)
print(r)

# q:
#  [[-0.857143  0.394286  0.331429]
#  [-0.428571 -0.902857 -0.034286]
#  [ 0.285714 -0.171429  0.942857]]
# r:
#  [[ -14.  -21.   14.]
#  [   0. -175.   70.]
#  [   0.    0.  -35.]]

In [ ]:
import scipy.linalg as la

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])

p, l, u = la.lu(a)
print(l)
print(u)
print(p)

In [ ]:
a = np.array([[3,1], [1,2]])
b = np.array([9,8])
x = np.linalg.solve(a, b)
print(x)

a = np.array([[1,2,3], [4,5,6], [7,8,10]])
b = np.array([9,4,6])
x = np.linalg.solve(a, b)
print(x)

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.linalg.inv(a)
print(x)

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])
x = np.matrix.transpose(a)
print(x)

In [ ]:
x = np.array([0.0, 1.0, 2.0, 3.0,  4.0,  5.0])
y = np.array([0.0, 0.8, 0.9, 0.1, -0.8, -1.0])
z = np.polyfit(x, y, 3)
print(z)

x = np.array([0.0, 1.0,  2.0,  3.0,  4.0,  5.0,   6.0,   7.0,   8.0,   9.0,  10.0]);
y = np.array([1.0, 6.0, 17.0, 34.0, 57.0, 86.0, 121.0, 162.0, 209.0, 262.0, 321.0]);
z = np.polyfit(x, y, 3)
print(z)

In [ ]:
import numpy as np

a = np.array([[4, 2, 1], [16, 4, 1], [64, 8, 1]])
u, s, vh = np.linalg.svd(a, full_matrices=True)

print(u)
print(s)
print(vh)

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
u, s, vh = np.linalg.svd(a, full_matrices=True)
print()
print(u)
print(s)
print(vh)

In [ ]:
import numpy as np

y = np.array([9,8,7,6])
x = np.array([1,3,1,1])
nd = y.ndim
print(y.shape)
print(len(y.shape))

axis = -1
dx = 1

# d = dx
d = np.diff(x)
print(d)

slice1 = [slice(None)]*nd
slice2 = [slice(None)]*nd
slice1[axis] = slice(1, None)
slice2[axis] = slice(None, -1)

print(slice1)
print(slice2)

print(tuple(slice1))
print(tuple(slice2))

print(y[tuple(slice1)])
print(y[tuple(slice2)])

print(np.trapz(y, x=x))

ret = (d * (y[tuple(slice1)] + y[tuple(slice2)]) / 2.0).sum(axis)
print(ret)



In [ ]:
def tupleset(t, i, value):
    l = list(t)
    l[i] = value
    return tuple(l)

y = np.array([9,8,7,6,5,4,3,2,1])
x = np.array([1,3,1,1])
axis = -1
dx = 1

N = y.shape[axis]
start = 0
stop = N - 2
step = 2

nd = len(y.shape)
if start is None:
    start = 0
step = 2
slice_all = (slice(None),)*nd
slice0 = tupleset(slice_all, axis, slice(start, stop, step))
slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

print(slice_all)
print(slice0)
print(slice1)
print(slice2)

print(y[slice0])
print(y[slice1])
print(y[slice2])

def _basic_simps(y, start, stop, x, dx, axis):
    nd = len(y.shape)
    if start is None:
        start = 0
    step = 2
    slice_all = (slice(None),)*nd
    slice0 = tupleset(slice_all, axis, slice(start, stop, step))
    slice1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
    slice2 = tupleset(slice_all, axis, slice(start+2, stop+2, step))

    if x is None:  # Even spaced Simpson's rule.
        result = np.sum(dx/3.0 * (y[slice0]+4*y[slice1]+y[slice2]),
                        axis=axis)
    else:
        # Account for possibly different spacings.
        #    Simpson's rule changes a bit.
        h = np.diff(x, axis=axis)
        sl0 = tupleset(slice_all, axis, slice(start, stop, step))
        sl1 = tupleset(slice_all, axis, slice(start+1, stop+1, step))
        h0 = h[sl0]
        h1 = h[sl1]
        hsum = h0 + h1
        hprod = h0 * h1
        h0divh1 = h0 / h1
        tmp = hsum/6.0 * (y[slice0]*(2-1.0/h0divh1) +
                          y[slice1]*hsum*hsum/hprod +
                          y[slice2]*(2-h0divh1))
        result = np.sum(tmp, axis=axis)
    return result

In [ ]:
from scipy import integrate

axis = -1
dx = 1
print(integrate.simps(y))

x = np.arange(0, 10)
y = np.arange(0, 10)

N = y.shape[axis]
start = 0
stop = N - 2
step = 2
axis = -1
dx = 1

print(integrate.simps(y, x=x))
print(integrate.trapz(y, x=x))

print(_basic_simps(y, start, stop, x, dx, axis))

x = np.asarray(x)
if len(x.shape) == 1:
    shapex = [1] * nd
    shapex[axis] = x.shape[0]
    saveshape = x.shape
    returnshape = 1
    x = x.reshape(tuple(shapex))
print(x)

print(_basic_simps(y, start, stop, x, dx, axis))

print(N % 2 == 0)

In [ ]:
slice1 = (slice(None),)*nd
slice2 = (slice(None),)*nd

print(x)

print(tupleset(slice1, axis, 0))
print(tupleset(slice2, axis, 1))

print(x[tuple(tupleset(slice1, axis, 0))])
print(x[tuple(tupleset(slice1, axis, 1))])

print(tupleset(slice1, axis, -1))
print(tupleset(slice2, axis, -2))
print(x[tuple(tupleset(slice1, axis, -1))])
print(x[tuple(tupleset(slice2, axis, -2))])

x = 0.0

x += np.array([1,2,3])
print(x + 50)

In [ ]:
x = np.linspace(-2, 2, num=20)
y = x
y_int = integrate.cumtrapz(y, x, initial=0)
print(y_int)

In [ ]:
y = np.array([1, 2, 3])
print(integrate.cumtrapz(y))
print(integrate.cumtrapz(y, initial=1))

In [ ]:
x = np.linspace(0, 2*np.pi, 100)
y = np.sin(x)

dy = np.zeros(y.shape,np.float)
print(dy)
dy[0:-1] = np.diff(y)/np.diff(x)
print(dy)
dy[-1] = (y[-1] - y[-2])/(x[-1] - x[-2])
dy

In [ ]:
import numpy as np

nyq = 1
cutoff = [0.1, 0.2, 0.3, 0.4]

cutoff = np.atleast_1d(cutoff) / float(nyq)

band = cutoff.reshape(-1, 2)
print(band)

for l, r in band:
    print(l, r)

pass_zero = False

print(cutoff.size)
print(cutoff.size & 1)

print(True ^ True)

pass_nyquist = bool(cutoff.size & 1) ^ pass_zero

print(pass_nyquist)

print([0.0] * False)

In [ ]:
import numpy as np
np.sinc([0.5 * np.pi, np.pi, (3 / 2) * np.pi, 2 * np.pi])

In [ ]:
import scipy as sp
sp.special.i0([0, 100, 0, 100])

In [ ]:
x = [1,2,3]
x[:-1]

In [103]:
from scipy import signal
window = signal.kaiser(51, beta=14)
window 

window = signal.kaiser(51, beta=14, sym=False)
window

signal.get_window(('kaiser', 4.0), 9)

signal.get_window(4.0, 9)

signal.get_window('black', 10)

array([-1.38777878e-17,  4.02128624e-02,  2.00770143e-01,  5.09787138e-01,
        8.49229857e-01,  1.00000000e+00,  8.49229857e-01,  5.09787138e-01,
        2.00770143e-01,  4.02128624e-02])

In [ ]:
import numpy as np

cutoff = np.array([0.5])
np.any(np.diff(cutoff))

In [ ]:
# https://stackoverflow.com/questions/1987694/how-to-print-the-full-numpy-array-without-truncation
import sys
import numpy as np
from scipy import signal as sg
import matplotlib.pyplot as plt
np.set_printoptions(threshold=sys.maxsize)

def plotSinal(t, x):
    plt.plot(t, x)
    plt.ylabel('Amplitude')
    plt.xlabel('Tempo (s)')
    plt.xlim(0, 10)
    plt.grid(True)
    plt.show()

# generate the signals
N = 50.0
fs = 128
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
sg1 = np.sin(n*2*np.pi*f1)

f2 = 10 # 10Hz
sg2 = np.sin(n*2*np.pi*f2)

sgF = sg1 + sg2

# print(sg1)
# print(sg2)
# print(sgF)
# print(n)

# design filter
nyq = 0.5 * fs
fc = 1
normal_fc = fc / nyq
numtaps = 30
b = sg.firwin(numtaps, [normal_fc])

# filter the signal
sgFiltered = sg.lfilter(b, [1.0], sgF)

# sgFiltered

# plotSinal(n, sg1)
# plotSinal(n, sgF)
# plotSinal(n, sgFiltered)

In [ ]:
import numpy as np

np.log10([0.1, 1, 10, 100])

In [ ]:
import numpy as np

def dbfft(x, fs, win=None, ref=32768):
    """
    Calculate spectrum in dB scale
    Args:
        x: input signal
        fs: sampling frequency
        win: vector containing window samples (same length as x).
             If not provided, then rectangular window is used by default.
        ref: reference value used for dBFS scale. 32768 for int16 and 1 for float

    Returns:
        freq: frequency vector
        s_db: spectrum in dB scale
    """

    N = len(x)  # Length of input sequence

    if win is None:
        win = np.ones(N)
    if len(x) != len(win):
            raise ValueError('Signal and window must be of the same length')
    x = x * win

    # Calculate real FFT and frequency vector
    sp = np.fft.rfft(x)
#     sp = sp[:len(sp)//2]
    print(sp)
    freq = np.arange((N / 2) + 1) / (float(N) / fs)

    # Scale the magnitude of FFT by window and factor of 2,
    # because we are using half of FFT spectrum.
    s_mag = np.abs(sp) * 2 / np.sum(win)

    # Convert to dBFS
    s_dbfs = 20 * np.log10(s_mag/ref)

    return freq, s_dbfs

# generate the signals
N = 10.0
fs = 128
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
sg1 = np.sin(n*2*np.pi*f1)

print(len(sg1))

dbs = dbfft(sg1, fs)
print(len(dbs[0]))
print(len(dbs[1]))
print(dbs)

In [97]:
x = np.array([1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0]);
np.fft.rfft(x)

# generate the signals
N = 10.0
fs = 128
n = np.linspace(0, N, num= int(N*fs), endpoint=False)

f1 = 1 # 1Hz
x = np.sin(n*2*np.pi*f1)

np.fft.rfft(x)

array([ 7.16433998e-15+0.00000000e+00j, -1.66780470e-16+1.17445974e-15j,
       -5.14774901e-15-2.89503125e-15j,  8.22650479e-16+2.02048296e-14j,
        2.00793123e-14+2.60555013e-14j, -1.88431519e-15+4.55100426e-14j,
       -1.27929643e-14+4.11602069e-14j, -1.06467451e-15+7.49809523e-14j,
        7.85321140e-15+1.14584948e-13j, -1.05647204e-14+2.27707268e-13j,
       -7.95807864e-13-6.40000000e+02j,  1.57778762e-14-2.63452131e-13j,
       -8.55596582e-15-1.33480168e-13j,  8.21176735e-15-9.38938111e-14j,
       -1.01577999e-14-6.33650672e-14j,  1.13441391e-14-7.58513783e-14j,
        1.21244496e-14-5.16992096e-14j,  7.64527505e-15-4.99006280e-14j,
       -2.46429500e-15-2.59738474e-14j,  2.70542158e-14-3.54651087e-14j,
        8.01414825e-15+5.70726706e-15j, -2.65484602e-14-3.44099379e-14j,
        9.87043006e-15-1.74590612e-14j, -7.60602395e-15-2.53554033e-14j,
        1.37195990e-14-2.66142227e-14j, -1.00568521e-14-6.53981023e-15j,
       -1.93987903e-14-2.24793719e-14j, -3.88411600